'use strict';
const $=id=>document.getElementById(id);
const categories=[{name:'Underweight (thin)',range:'BMI < 18.5',file:'underweight',alt:'Illustrated adult with a slender build',text:'Below the normal range.',color:'#e5f0f6'},{name:'Normal',range:'18.5 ≤ BMI < 24',file:'normal',alt:'Illustrated adult with a medium build',text:'In the normal range.',color:'#edf3df'},{name:'Overweight',range:'24 ≤ BMI < 27',file:'overweight',alt:'Illustrated adult with a rounded build',text:'Above the normal range.',color:'#fcf0dc'},{name:'Obesity',range:'BMI ≥ 27',file:'obesity',alt:'Illustrated adult with a larger build',text:'In the obesity range.',color:'#f8e6e1'}];
function categoryIndex(bmi){return bmi<18.5?0:bmi<24?1:bmi<27?2:3}
function updateScale(value,resize){const slider=$('bmi-slider');if(resize){slider.min=String(Math.min(1,value));slider.max=String(Math.max(40,Math.ceil(value/10)*10));}const min=Number(slider.min),max=Number(slider.max),pct=v=>(v-min)/(max-min)*100;slider.style.setProperty('--track',`linear-gradient(to right,#bcdce9 0% ${pct(18.5)}%,#cce2a9 ${pct(18.5)}% ${pct(24)}%,#f0d096 ${pct(24)}% ${pct(27)}%,#e8bcb2 ${pct(27)}% 100%)`);const ticks=max<=60?[min,18.5,24,27,max]:[min,max/2,max];$('bmi-ticks').innerHTML=ticks.map(n=>`<path d="M${pct(n)*6} 3v7" stroke="#6b806e"/><text x="${pct(n)*6}" y="31" text-anchor="middle" font-family="Segoe UI, sans-serif" font-size="15" fill="#526b59">${Number(n.toFixed(2))}</text>`).join('');}
function showBMI(value,source){if(!Number.isFinite(value)||value<=0)return;updateScale(value,source==='calculate');$('bmi-slider').value=String(value);const c=categories[categoryIndex(value)];$('bmi-value').textContent=value.toFixed(2);$('character-bmi').textContent=value.toFixed(2);$('body-image').src=`assets/${c.file}.png`;$('body-image').alt=c.alt;$('category-name').textContent=c.name;$('category-range').textContent=c.range;$('category-explanation').textContent=c.text;document.querySelector('.character-panel').style.setProperty('--category-bg',c.color);$('bmi-slider').setAttribute('aria-valuetext',`${value.toFixed(2)} — ${c.name}`);$('slider-hint').textContent=(source==='calculate'?'Calculated result · 計算結果已同步滑桿。':'Slider mode · 現在顯示滑桿探索值。')+' '+c.range;}
$('bmi-slider').addEventListener('input',e=>{const v=Number(e.target.value);showBMI(v,'slider');$('calculation').textContent='Slider mode · 拖曳探索中。';$('calculation').className='small'});
// Keep a predictable 0.1 keyboard increment even with step="any" for exact calculated values.
$('bmi-slider').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowDown','ArrowUp'].includes(e.key))return;e.preventDefault();const sign=['ArrowLeft','ArrowDown'].includes(e.key)?-1:1;const value=Math.min(Number(e.target.max),Math.max(Number(e.target.min),Number((Number(e.target.value)+sign*.1).toFixed(2))));e.target.value=value;e.target.dispatchEvent(new Event('input',{bubbles:true}))});
document.querySelectorAll('[data-bmi]').forEach(b=>b.addEventListener('click',()=>{showBMI(Number(b.dataset.bmi),'slider');$('calculation').textContent='Example · 範例數值。';$('calculation').className='small'}));
$('bmi-form').addEventListener('submit',e=>{e.preventDefault();const h=Number($('height').value),w=Number($('weight').value);const heightOK=Number.isFinite(h)&&h>=30&&h<=300,weightOK=Number.isFinite(w)&&w>=1&&w<=1000;$('height').setAttribute('aria-invalid',String(!heightOK));$('weight').setAttribute('aria-invalid',String(!weightOK));if(!heightOK||!weightOK){$('calculation').textContent='Check your inputs · 請輸入身高 30–300 公分、體重 1–1000 公斤的有效數字；數值不可空白或為 0。圖片仍顯示上一個有效值。';$('calculation').className='small error';(!heightOK?$('height'):$('weight')).focus();return}const bmi=w/(h/100)**2;showBMI(bmi,'calculate');$('calculation').className='small';$('calculation').textContent=`${w} ÷ (${h} ÷ 100)² = ${Number(bmi.toPrecision(12))}`;});
showBMI(20,'slider');
